Feature/switch to fluentui
Seitenbau/RoomieReloaded pull request #51
Opened 2023-08-11 10:17 UTC by BlameFelix

Bis auf die Button verschiebung konnte ich keine probleme feststellen

2023-08-17 13:31 UTC, MaxAtoms requested changes
Eine Sache ist mir noch aufgefallen:
Der DatePicker wechselt nicht mehr richtig in den Dark Mode.

![image](https://github.com/Seitenbau/RoomieReloaded/assets/7847075/4303f1cc-9aa1-4956-8442-a52fefb73889)

Hab heute leider keine Zeit mehr, um genauer reinzuschauen.
Alles andere scheint in der Tat weiterhin zu funktionieren :)

2023-08-17 13:31 UTC, MaxAtoms commented on RoomieReloaded/ClientApp/src/components/navigation/navigation.css
> +    width: 32px;
Die Width hat laut Browsertools keine Auswirkung im Dark Mode.
Im Dark Mode ist der Button mit 40px richtig dimensioniert, im Light Mode jedoch greifen die 32px und dann ist der Button schmaler als die anderen (╯°□°)╯︵ ┻━┻

Was mir bisher nie aufgefallen ist: Wenn man rechts vom Kalendericon auf den Div/Button klickt,
dann passiert gar nichts (das ist allerdings nichts neues).

2023-08-18 06:58 UTC, BlameFelix commented on RoomieReloaded/ClientApp/src/components/navigation/navigation.css
> +    width: 32px;
Hmm interessant, ich schau mal genauer, sobald ich wieder Zeit habe...

2023-09-01 08:24 UTC, BlameFelix commented on RoomieReloaded/ClientApp/src/components/navigation/navigation.css
> +    width: 32px;
Das mit der Größe, bzw der Verschiebung des Icons sollte nun behoben sein. Mir ist ehrlich gesagt nicht ganz klar, warum gewisse Styles nur im Darkmode gesetzt sind und wie das bisher überhaupt funktioniert hat aber gut :D

2025-07-25 13:23 UTC, merged